<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-11-09 17:01
=======
# Generated by Django 5.2.7 on 2025-11-05 14:40
>>>>>>> b25a1eac75d8df2e4d53e6ea5f5f275cef259bb3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('quiz', '0003_alter_quiz_timer'),
=======
        ('quiz', '0002_quiz_timer_quiz_total_questions_question'),
>>>>>>> b25a1eac75d8df2e4d53e6ea5f5f275cef259bb3
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_answers', to='attempts.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
=======
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts_by_code', to='quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts_by_title', to='quiz.quiz')),
>>>>>>> b25a1eac75d8df2e4d53e6ea5f5f275cef259bb3
            ],
        ),
    ]
