# Generated by Django 5.2.7 on 2025-11-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_alter_attempt_student'),
        ('quiz', '0002_quiz_timer_quiz_total_questions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='code',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='title',
        ),
        migrations.AddField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
