# Generated by Django 5.2.7 on 2025-11-07 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_remove_attempt_code_remove_attempt_title_and_more'),
        ('quiz', '0002_quiz_timer_quiz_total_questions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='quiz',
        ),
        migrations.AddField(
            model_name='attempt',
            name='code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts_by_code', to='quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts_by_title', to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
