# Generated by Django 5.2.6 on 2025-11-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_rename_code_attempt_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedanswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
