# Generated by Django 5.2.6 on 2025-11-16 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0004_alter_savedanswer_selected_option'),
        ('quiz', '0003_alter_quiz_timer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('student', 'quiz')},
        ),
    ]
