# Generated by Django 5.2.8 on 2025-11-16 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0005_alter_attempt_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='savedanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attempts.attempt'),
        ),
        migrations.AlterField(
            model_name='savedanswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
