# Generated by Django 5.2.6 on 2025-11-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_timer_quiz_total_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='timer',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
